#!/bin/sh

echo $0 start at $(date)

# make sure we never run 2 rsync at the same time
lockfile="/tmp/alpine-mirror.lock"
if [ -z "$flock" ] ; then
  exec env flock=1 flock -n $lockfile "$0" "$@"
fi


dest=/mirror

. /etc/alpine-mirror.conf
echo exclude: $exclude
echo src: $src

mkdir -p "$dest"
/usr/bin/rsync \
        --archive \
        --update \
        --hard-links \
        --delete \
        --delete-after \
        --delay-updates \
        --timeout=600 \
	$exclude \
        "$src" "$dest"

echo $0 finish at $(date)
