#!/bin/bash

. ../conf/app.conf
. ../conf/internal.conf

echo IMAGE: $IMAGE
echo CONTAINER: $CONTAINER
echo DOWNLOAD_PATH: $DOWNLOAD_PATH
echo INER_DOWNLOAD_PATH: $INER_DOWNLOAD_PATH
echo APP_CACHE_DIR: $APP_CACHE_DIR
echo CONF_FILE: $CONF_FILE
echo SESSION_FILE: $SESSION_FILE

[ -d $DOWNLOAD_PATH/$APP_CACHE_DIR ] || echo mkdir.... && mkdir -p $DOWNLOAD_PATH/$APP_CACHE_DIR
[ -f $DOWNLOAD_PATH/$APP_CACHE_DIR/$CONF_FILE ] || cp -v ../image/$CONF_FILE $DOWNLOAD_PATH/$APP_CACHE_DIR/
[ -f $DOWNLOAD_PATH/$APP_CACHE_DIR/$SESSION_FILE ] || touch $DOWNLOAD_PATH/$APP_CACHE_DIR/$SESSION_FILE

docker run --name=$CONTAINER -d --restart=always -v $DOWNLOAD_PATH:$INER_DOWNLOAD_PATH -p 6800:6800 -p 6789:80 -it $IMAGE
